# Site settings
title: Notes Audio
email: support@notesaudio.com
description: Notes Audio là một công ty khởi nghiệp trẻ tập trung phát triển các sản phẩm tai nghe và thiết bị âm thanh di động - có trụ sở tại Việt Nam
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.notesaudio.com" # the base hostname & protocol for your site
facebook_username: notesaudio
twitter_username: notesaudio
github_username:  notesaudio

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
